### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by johnny-stevie** [championswimmer/nativescript-awesome-webview#3]
### Which platform(s) does your issue occur on?
Android
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.3
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
On an image, the ontap attribute points to a function where i execute the awesome-webview code. I think it is coming from the com.android.support.customTabs native package, my compiler isnt very fond of using native libs, it always gives an undefined error.

### Is there any code involved?
imported required modules  
`init(); 
openWebView({
      url: 'http://google.com',
      toolbarColor: '#2277aa',
      toolbarControlsColor: '#eebb99'
    });
`
error
`JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'extend' of undefined
JS: TypeError: Cannot read property 'extend' of undefined
JS:     at init (file:///data/data/org.nativescript.AngularYt/files/app/vendor.js:91562:69)
JS:     at new VideoComponent file:///src\app\video\video.component.ts:32:8
JS:     at createClass file:///node_modules\@angular\core\fesm5\core.js:19396:0
JS:     at createDirectiveInstance file:///node_modules\@angular\core\fesm5\core.js:19271:0
JS:     at createViewNodes file:///node_modules\@angular\core\fesm5\core.js:27489:0
JS:     at createRootView file:///node_modules\@angular\core\fesm5\core.js:27403:0
JS:     at callWithDebugContext file:///node_modules\@angular\core\fesm5\core.js:28411:0
JS:     at Object.debugCreateRootView [as createRootView] file:///node_modules\@angular\core\fesm5\core.js:27921:0
JS:     at ComponentFactory_.push...
`

**Comment by kcabhish** [comment]
I am getting the same issue when i try to run the example from the package
```
    openWebView({
      url: 'http://google.com',
      toolbarColor: '#2277aa',
      toolbarControlsColor: '#eebb99'
    });
```

```
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'extend' of undefined
System.err: File: (file:///node_modules/nativescript-awesome-webview/awesome-webview.js:14:0)
System.err: 
System.err: StackTrace: 
System.err: 	init(file:///node_modules/nativescript-awesome-webview/awesome-webview.js:14:0)
System.err: 	at (file:///app/main-page.ts:19:4)
System.err: 	at ./main-page.ts(file:///data/data/com.wapo.slate.android/files/app/bundle.js:475:30)
System.err: 	at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err: 	at fn(file:///app/webpack/bootstrap:120:0)
System.err: 	at (file:///app/app.ts:1:0)
System.err: 	at ./app.ts(file:///data/data/com.wapo.slate.android/files/app/bundle.js:238:30)
System.err: 	at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err: 	at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
System.err: 	at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
System.err: 	at (file:///data/data/com.wapo.slate.android/files/app/bundle.js:2:57)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'extend' of undefined
```

**Comment by johnny-stevie** [comment]
i moved to the advanced webview plugin, it ran much smoother.
